### ISSUE TITLE
Spider: Detroit Board of Ethics

### ISSUE THREAD

**Issue by cascio** [City-Bureau/city-scrapers#710] opened 2019-03-18 21:41 UTC
URL: [https://detroitmi.gov/Calendar-and-Events](https://detroitmi.gov/Calendar-and-Events)
Spider Name: `det_boardofethics`
Agency Name: Detroit Board of Ethics

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

This scraper is part of the general Detroit website which does a good job standardizing meeting information so most of the work is done for you in [`DetCityMixin`](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/mixins/det_city.py).

To pull most of the information for a general detroitmi.gov scraper, you need to go to the [events page](https://detroitmi.gov/Calendar-and-Events), filter for the agency in the Government select field, and then get the ID that shows up next to `term_node_tid_depth_1=` on the results page URL.

Then, to pull any related documents, go the the [documents page](https://detroitmi.gov/documents), look for relevant document categories in the Government autocomplete field, filter for them, and then pull the ID from the parameter in the results page URL that follows `field_department_target_id_1`. On initial filter, it will pull in a label too (ex. for the City Planning Commission it shows `City+Planning+Commission+Minutes+(3761))` but you only need the number in parentheses.

Once you've included that information, you can override methods like _parse_title if the defaults aren't right, and you'll still need to implement _parse_classification. See `det_city_planning` or `det_zoning_appeals` for some examples

**Comment by iandbell** [comment] 2019-04-09 02:43
I'd like to work on this if I may.

**Comment by pjsier** [comment] 2019-04-09 12:29
@iandbell sounds good, feel free to reach out with questions!

**Comment by nbearman** [comment] 2019-04-16 21:57
Hello,
I'm also giving this a try, if that's alright (for educational purposes; definitely not trying to step on any toes).

I ran into a problem I believe is with the Detroit City Mixin (mixins/det_city.py, around line 207) where an improperly handled date format ("Aug" instead of "August") was causing errors. Would it be outside the scope of this issue to address the problem by changing the Detroit City Mixin?

Thanks for any guidance, and please let me know also if this kind of thing would be better handled on the Slack.

**Comment by pjsier** [comment] 2019-04-16 22:06
@nbearman if you’re interested in working on the mixin, the Detroit Department of Transportation is another agency that would use it that I haven’t created an issue for yet. Would that work? Feel free to make an issue like this if it does! I can also make the issue for you

**Comment by nbearman** [comment] 2019-04-20 16:50
@pjsier If you'd be willing to create the issue, that'd be great, thanks.

**Comment by nolanee** [comment] 2019-10-02 22:11
Is help still needed with this? I would like to contribute, if I may.

**Comment by pjsier** [comment] 2019-10-02 22:16
@nolanee all yours since it's been inactive!

**Comment by nolanee** [comment] 2019-10-03 04:42
It seems like there aren't any events for this agency?

**Comment by pjsier** [comment] 2019-10-03 12:24
Gotcha, the issue is from a bit ago, but up to you whether it's still worth doing. They might post them in the future, but you're also welcome to take a look at another issue

**Comment by nolanee** [comment] 2019-10-03 20:07
Okay! I'm happy to keep working on this issue, but I was just wondering whether you have any advice on how to work on the scraper and write tests for it, given that I don't have an example of html with an event from that agency that has the agency id etc.

**Comment by pjsier** [comment] 2019-10-03 21:16
There's a specific setup for Detroit scrapers that would make it easier, but since you wouldn't be able to write tests easily it's probably best to see if there's another issue that works

**Comment by luchiago** [comment] 2019-11-22 19:36
Is this issue still need help?

**Comment by pjsier** [comment] 2019-11-30 21:32
No events online, closing

**Closed by pjsier** 2019-11-30 21:32 UTC
Labels: good first issue, location: detroit, new spider needed
